### ISSUE TITLE
using "options" to save the record

### ISSUE THREAD

**Issue by casiopeus** [kakone/VLC.MediaElement#11]
Hello again. Im trying to use the "Options" field of the vlc.MediaElement to save the recording in a file.

Launching Vlc.exe desktop version from command prompt i don´t have problems to save videos from youtube and from my ip camera, but inside the apllication it seems it doesn´t work.

I am using this way before "Source" field
MediaElement.Options.Add("--sout-keep", true);
MediaElement.Options.Add("--sout #duplicate{dst=file{dst=FILENAME.AVI},dst=display}");
It didn´t worked

And the command line with it works from desktop version is:

C:\-Path-\VLC\vlc.exe http://url --sout #duplicate{dst=file{dst="FILENAME.AVI"},dst=display} --sout-keep

Do you know it is a correct way to record video or could be another way to record the streaming??

TYSM developers!

**Comment by kakone** [comment]
For the options, you should not include the ‘--'.
But, anyway, only a small subset of VLC options is available in libVLC for UWP. I don't think it's possible to record the video for the moment (that's why the option doesn't exist in [VLC for UWP](https://www.microsoft.com/fr-fr/store/p/vlc/9nblggh4vvnh)).

**Comment by casiopeus** [comment]
So, do you know i could saving the value of MediaElement.Source in .avi file as soon as it comes from camera?. For example using StorageFile or something like that?. How do you think it could be possilbe?
