### ISSUE TITLE
libvlcx

### ISSUE THREAD

**Issue by clark-yang** [kakone/VLC.MediaElement#13]
HI.
First of all, thank you for your work. I used libvlcx for uwp, but there is no audio in mobile and pc, can you tell  me the reasons.

**Comment by kakone** [comment]
You use libvlcx directly ? Or the VLC.MediaElement ?

You can try to play your video with [VLC for UWP](https://www.microsoft.com/store/p/vlc/9nblggh4vvnh). If it works with VLC for UWP, it should work with VLC.MediaElement. Otherwise, you can create a new issue [here](https://code.videolan.org/videolan/vlc-winrt/issues/) with a sample.

**Comment by clark-yang** [comment]
At first, I used the VLC.Mediamlement in xaml, but I can't startup the application, it will throw a exception(System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.at Windows.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)　) when initialize component． Then I use libvlcx directly，but there is no audio in mobile and pc．

**Comment by kakone** [comment]
Strange exception, it would be nice if you could run the VLC.MediaElement code in debug mode to understand the cause of the problem.
Otherwise, with libVLCX, did you add the line `mediaPlayer.outputDeviceSet(AudioDevice.audioClient());` ?

**Comment by LeeParrish** [comment]
I saw the same exception: System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.at Windows.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize) and found that it happens when the target version of the project is earlier than Anniversary Edition (10.0, Build 14393). I believe it's due to some ThemeResource values that are referenced in Generic.xaml that are missing in earlier builds. You see this if you try to compile VLCMediaElement against any version earlier then 14393 in that it gives 3 errors during compile. But if you add from nuget it will happily add to a project earlier than 14393 and then you see the exception noted above during runtime.
